version: '3.8'

services:
  db:
    image: mariadb:10.11
    container_name: partikulier_db
    restart: always
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:6.6-php8.3-apache
    container_name: partikulier_app
    restart: always
    ports:
      - "8090:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wp
    volumes:
      - ./theme:/var/www/html/wp-content/themes/partikulier
      - ./mu-plugins:/var/www/html/wp-content/mu-plugins

volumes:
  db_data:
