<?php
require_once __DIR__ . '/lib-n8n-test.php';
$name = defined( 'PK_N8N_TEST_NAME' ) ? PK_N8N_TEST_NAME : basename( $_SERVER['SCRIPT_FILENAME'] ?? 'unknown' );
$secret = base64_encode( random_bytes( 32 ) );
$previous = base64_encode( random_bytes( 32 ) );
$original = pk_n8n_settings_snapshot();
try {
	pk_n8n_test_run( $name, function ( $report ) use ( $name, $secret, $previous, $original ) {
			if ( 'test-n8n-settings-migration.php' === $name ) {
				$legacy = get_option( Partikulier_Settings::OPTION, array() );
				update_option( Partikulier_Settings::OPTION, array_merge( is_array( $legacy ) ? $legacy : array(), array( 'automation_api_secret' => $secret, 'n8n_webhook_url' => 'https://example.invalid/hook' ) ), false );
				delete_option( Partikulier_N8n_Security::OPTION ); delete_option( Partikulier_N8n_Security::MIGRATION_OPTION );
				Partikulier_N8n_Security::maybe_migrate(); Partikulier_N8n_Security::maybe_migrate();
				$s = pk_n8n_settings_snapshot(); pk_n8n_assert( is_array( $s ) && $s['automation_api_secret'] === $secret, 'migration secret absent' ); pk_n8n_assert( 'completed' === get_option( Partikulier_N8n_Security::MIGRATION_OPTION ), 'migration not completed' ); pk_n8n_assert( Partikulier_N8n_Security::get( 'automation_api_secret' ) === $secret, 'read order invalid' );
				$report['checks'][] = 'migration_idempotente_reprise_completed';
			} elseif ( 'test-n8n-hmac-modes.php' === $name ) {
				update_option( Partikulier_N8n_Security::OPTION, array( 'automation_api_secret' => $secret, 'active_key_id' => 'N' ), false );
				$body = array( 'event_id' => 'n8n-hmac-' . wp_generate_uuid4(), 'event_type' => 'whatsapp_status', 'source' => 'n8n', 'payload' => array( 'ok' => true ) );
				foreach ( array( 'off', 'log', 'enforce' ) as $mode ) { update_option( Partikulier_N8n_Security::OPTION, array( 'automation_api_secret' => $secret, 'active_key_id' => 'N', 'hmac_mode' => $mode ), false ); $bad = pk_n8n_request( 'POST', '/partikulier/v1/automation-event', $body, array( 'X-Partikulier-Automation' => $secret ) ); $bad_result = Partikulier_N8n_Security::check_automation_secret( $bad ); pk_n8n_assert( ( 'enforce' === $mode ) ? is_wp_error( $bad_result ) : true, 'mode ' . $mode . ' unexpected invalid-signature result' ); }
				$good = pk_n8n_request( 'POST', '/partikulier/v1/automation-event', $body, array_merge( array(), pk_n8n_hmac_headers( 'POST', '/partikulier/v1/automation-event', $body, $secret, 'N' ) ) ); update_option( Partikulier_N8n_Security::OPTION, array( 'automation_api_secret' => $secret, 'active_key_id' => 'N', 'hmac_mode' => 'enforce' ), false ); pk_n8n_assert( true === Partikulier_N8n_Security::check_automation_secret( $good ), 'valid HMAC rejected' ); $report['checks'][] = 'off_log_enforce_secret_required';
			} elseif ( 'test-n8n-replay.php' === $name ) {
				update_option( Partikulier_N8n_Security::OPTION, array( 'automation_api_secret' => $secret, 'active_key_id' => 'N', 'hmac_mode' => 'enforce' ), false ); $body = array( 'event_id' => 'n8n-replay-' . wp_generate_uuid4(), 'event_type' => 'whatsapp_status', 'source' => 'n8n', 'payload' => array( 'id' => 1 ) ); $old = pk_n8n_request( 'POST', '/partikulier/v1/automation-event', $body, pk_n8n_hmac_headers( 'POST', '/partikulier/v1/automation-event', $body, $secret, 'N', time() - 301 ) ); pk_n8n_assert( is_wp_error( Partikulier_N8n_Security::check_automation_secret( $old ) ), 'expired timestamp accepted' ); $response = Partikulier_Automation_Bridge::receive_event( pk_n8n_request( 'POST', '/partikulier/v1/automation-event', $body ) ); pk_n8n_assert( ! is_wp_error( $response ), 'first event failed' ); $duplicate = Partikulier_Automation_Bridge::receive_event( pk_n8n_request( 'POST', '/partikulier/v1/automation-event', $body ) ); pk_n8n_assert( ! is_wp_error( $duplicate ) && true === $duplicate->get_data()['duplicate'], 'duplicate not reported' ); $report['checks'][] = 'timestamp_replay_and_event_id_duplicate';
			} elseif ( 'test-n8n-secret-rotation.php' === $name ) {
				update_option( Partikulier_N8n_Security::OPTION, array( 'automation_api_secret' => $secret, 'active_key_id' => 'N', 'previous_secret' => $previous, 'previous_key_id' => 'N-1', 'previous_expires_at' => gmdate( 'c', time() + 600 ), 'hmac_mode' => 'enforce' ), false ); $body = array( 'event_id' => 'n8n-rotation-' . wp_generate_uuid4() ); $old = pk_n8n_request( 'POST', '/partikulier/v1/automation-event', $body, pk_n8n_hmac_headers( 'POST', '/partikulier/v1/automation-event', $body, $previous, 'N-1' ) ); pk_n8n_assert( true === Partikulier_N8n_Security::check_automation_secret( $old ), 'previous key rejected during overlap' ); update_option( Partikulier_N8n_Security::OPTION, array( 'automation_api_secret' => $secret, 'active_key_id' => 'N', 'previous_secret' => $previous, 'previous_key_id' => 'N-1', 'previous_expires_at' => gmdate( 'c', time() - 1 ), 'hmac_mode' => 'enforce' ), false ); pk_n8n_assert( is_wp_error( Partikulier_N8n_Security::check_automation_secret( $old ) ), 'expired previous key accepted' ); $report['checks'][] = 'dual_key_overlap_expiry';
			} elseif ( 'test-n8n-idempotence-race.php' === $name ) {
				$body = array( 'event_id' => 'n8n-race-' . wp_generate_uuid4(), 'event_type' => 'whatsapp_status', 'source' => 'n8n', 'payload' => array( 'race' => true ) ); $one = Partikulier_Automation_Bridge::receive_event( pk_n8n_request( 'POST', '/partikulier/v1/automation-event', $body ) ); $two = Partikulier_Automation_Bridge::receive_event( pk_n8n_request( 'POST', '/partikulier/v1/automation-event', $body ) ); pk_n8n_assert( ! is_wp_error( $one ) && ! is_wp_error( $two ), 'race request failed' ); pk_n8n_assert( true === ( $two->get_data()['duplicate'] ?? false ), 'race duplicate false' ); $report['checks'][] = 'insert_duplicate_path';
			} elseif ( 'test-n8n-route-guard.php' === $name ) {
				$routes = rest_get_server()->get_routes(); $automation = array(); foreach ( $routes as $route => $handlers ) { if ( 0 === strpos( $route, '/partikulier/v1/' ) ) { foreach ( $handlers as $handler ) { if ( isset( $handler['permission_callback'] ) && is_array( $handler['permission_callback'] ) && 'Partikulier_Automation_Bridge' === ( $handler['permission_callback'][0] ?? '' ) ) { $automation[] = $route; } } } } pk_n8n_assert( count( $automation ) >= 7, 'shared route guard did not cover expected automation routes' ); $report['checks'][] = 'routes_shared_callback_' . count( $automation );
			} elseif ( 'test-n8n-canary.php' === $name ) {
				$hash = substr( hash( 'sha256', $secret ), 0, 16 ); $paths = array( ABSPATH . '../partikulier-6.16.0.zip', dirname( __DIR__ ) . '/rapport-6.16.0' ); foreach ( $paths as $path ) { if ( file_exists( $path ) ) { pk_n8n_assert( false === strpos( (string) file_get_contents( $path ), $secret ), 'secret canary leaked' ); } } $report['checks'][] = 'canary_fingerprint_only_' . $hash;
			} else { throw new RuntimeException( 'unknown test script' ); }
			return $report;
		} );
} finally { pk_n8n_restore_snapshot( $original ); }
